CREATE USER __USER__ WITH PASSWORD '__PW__';
GRANT ALL PRIVILEGES ON DATABASE __DB__ TO __USER__;
GRANT CONNECT ON DATABASE __DB__ TO __USER__;

CREATE USER __RUSER__ WITH PASSWORD '__RPW__';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO __RUSER__;
